### ISSUE TITLE
Any way to intercept outgoing HTTP requests form the webview?

### ISSUE THREAD

**Issue by leomorpho** [bettysteger/flutter_pwa_wrapper#2]
Thanks a lot for creating this package @bettysteger !!! When performing HTTP requests, I want to send to my BE some data point (either http query param or header) so that I can return the correct data based on whether the BE is dealing with a PWA, an iOS or Android platform. I am currently attempting to find a way of doing this but am struggling on it. 
Have you, by any chance, had to do that? Is there an alternative method for the BE to determine which platform the request came from?

**Comment by bettysteger** [comment]
At the moment i use this in my JS, but not 100% sure if it still works:

```
let isInsideApp = !!window.flutterChannel;
const IS_INSIDE_APP = isInsideApp || (document.referrer && document.referrer.indexOf('android-app://') === 0);
```

and checking if not the flutter app, but the PWA is installed:

```
let installedPwa = false;
try {
  installedPwa = window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone;
} catch (e) { }
const IS_INSTALLED_PWA = installedPwa;
```

**Comment by leomorpho** [comment]
Hah! Never mind, I can just look at the user agent string on the BE.
I changed the default useragenct strings to 
```dart
  static const androidUserAgent =
      "Mozilla/5.0 (Linux; Android 8.0; Pixel 2 Build/OPD3.170816.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Mobile Safari/537.36";
  static const iosUserAgent =
      "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15A372 Safari/604.1";
```
and then used dart:io to determine if it's iOS:
```dart
String userAgent =
        Platform.isIOS ? SETTINGS.iosUserAgent : SETTINGS.androidUserAgent;
```

and then it's set with the existing `..setUserAgent(userAgent)`.

**Comment by bettysteger** [comment]
ah ok yeah that makes total sense! 

Another approach is adding an additional JS function to the existing `javaScriptFunction` in `lib/main.dart`: 

``` 
    void javaScriptFunction (JavaScriptMessage message) async {
      if(message.message == 'getPushToken') {
        ...
      }
      if (message.message == 'getPlatform') { 
        webviewController.runJavaScript("setPlatform(\"${Platform.operatingSystem}\")");
      }
    }
 ```
 
 And then it your JS:
 
 ```
 window.flutterChannel.postMessage('getPlatform')
 function setPlatform(platform) { ... } // returns android or ios
 ```
